[versions]
paper = "1.19.4-R0.1-SNAPSHOT"
commandapi = "9.0.0"
checkerframework = "3.33.0"

[libraries]
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
commandapi-shade = { module = "dev.jorel:commandapi-bukkit-shade", version.ref = "commandapi" }
checker-qual = { module = "org.checkerframework:checker-qual", version.ref = "checkerframework" }