[versions]
paper = "1.21-R0.1-SNAPSHOT"
commandapi = "9.5.1"
checkerframework = "3.33.0"
jetbrains-annotations = "23.1.0"
adventure = "4.17.0"

[libraries]
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
commandapi-shade = { module = "dev.jorel:commandapi-bukkit-shade-mojang-mapped", version.ref = "commandapi" }
checker-qual = { module = "org.checkerframework:checker-qual", version.ref = "checkerframework" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
adventure = { module = "net.kyori:adventure-api", version.ref = "adventure" }
minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }